raw_get_positions:
  target:
    entity:
      domain: vacuum
      integration: ecovacs

raw_get_map_info:
  target:
    entity:
      domain: vacuum
      integration: ecovacs

raw_get_map_set:
  target:
    entity:
      domain: vacuum
      integration: ecovacs

raw_get_map_set_decoded:
  target:
    entity:
      domain: vacuum
      integration: ecovacs

raw_get_quick_commands:
  target:
    entity:
      domain: vacuum
      integration: ecovacs
